### ISSUE TITLE
[BUG] 使用自动熔炼时，熔炼产物数量可能不足

### ISSUE THREAD

**Issue by CloudSail1** [Yanxiyimengya/SmithyLegend#4]
版本：1.1.0
启用升级：自动熔炼
点击自动熔炼后，产物会飞向熔炉，但正在飞行的物品似乎并没有进入熔炉，因此即使熔炉容量已满，后续物品仍然会飞进熔炉然后归于虚无。这种情况在连续点击自动熔炼时很常见，比方说如果我有两个容量为4的熔炉，连续点击八次自动熔炼，只要我点的够快，可能只能得到4个，因为所有的物品都飞进第一个熔炉了。但如果我点4次之后，等待四个物品都非进熔炉，再点击4次，就不会出现任何问题。

**Comment by Yanxiyimengya** [comment]
这不是一个bug，你可以把它看作你点击过快带来的惩罚
